<?
require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/header.php");
$APPLICATION->SetTitle("Yandex market");
//global $arrFilter; $arrFilter = array("!PROPERTY_CML2_MANUFACTURER" => false);
?>
<? $APPLICATION->IncludeComponent(
	"nf:yandex.market_new", 
	"vendor.model",
	array(
		"IBLOCK_TYPE" => "%_catalog",
		"IBLOCK_ID_IN" => array(
			0 => "136",
		),
		"IBLOCK_ID_EX" => array(
			0 => "0",
		),
		"IBLOCK_SECTION" => array(
			0 => "0",
		),
		"SITE" => "24poligo.ru",
		"COMPANY" => "Военторг 'Полигон'",
		"FILTER_NAME" => "arrFilter",
		"MORE_PHOTO" => "MORE_PHOTO",
		"CACHE_TYPE" => "Y",
		"CACHE_TIME" => "43000",
		"CACHE_FILTER" => "Y",
		"PRICE_CODE" => array(
			0 => "Розничная цена",
		),
		"IBLOCK_ORDER" => "N",
		"CURRENCY" => "RUR",
		"LOCAL_DELIVERY_COST" => "300",
		"COMPONENT_TEMPLATE" => "vendor.model",
		"IBLOCK_CATALOG" => "Y",
		"DO_NOT_INCLUDE_SUBSECTIONS" => "N",
		"IBLOCK_AS_CATEGORY" => "Y",
		"CACHE_NON_MANAGED" => "Y",
		"DEVELOPER" => "PROIZVODITEL",
		"COUNTRY" => "EMPTY",
		"SKU_NAME" => "PRODUCT_NAME",
		"SKU_PROPERTY" => "PROPERTY_CML2_LINK",
		"CURRENCIES_CONVERT" => "NOT_CONVERT",
		"OLD_PRICE_LIST" => "FROM_DISCOUNT",
		"NAME_PROP" => "0",
		"DETAIL_TEXT_PRIORITET" => "N",
		"PARAMS" => array(
		),
		"COND_PARAMS" => array(
		),
		"SELF_SALES_NOTES" => "Y",
		"SALES_NOTES_NAMES" => "0",
		"DISCOUNTS" => "DISCOUNT_CUSTOM",
		"CHECK_PRICE_FROM_PROM" => "N",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"TYPE" => "EMPTY",
		"PROPERTY_TYPE" => "EMPTY",
		"CATEGORY" => "EMPTY",
		"CREATION_DATE" => "EMPTY",
		"LAST_UPDATE_DATE" => "EMPTY",
		"EXPIRE_DATE" => "EMPTY",
		"PAYED_ADV" => "EMPTY",
		"MANUALLY_ADDED" => "EMPTY",
		"REGION" => "EMPTY",
		"DISTRICT" => "EMPTY",
		"LOCALITY_NAME" => "EMPTY",
		"ADDRESS" => "EMPTY",
		"SUB_LOCALITY_NAME" => "EMPTY",
		"NON_ADMIN_SUB_LOCALITY_NAME" => "EMPTY",
		"DIRECTION" => "EMPTY",
		"DISTANCE" => "EMPTY",
		"LATITUDE" => "EMPTY",
		"LONGITUDE" => "EMPTY",
		"RAILWAY_STATION" => "EMPTY",
		"METRO_NAME" => "EMPTY",
		"METRO_TIME_ON_TRANSPORT" => "EMPTY",
		"METRO_TIME_ON_FOOT" => "EMPTY",
		"AGENT_NAME" => "EMPTY",
		"AGENT_PHONE" => "EMPTY",
		"AGENT_CATEGORY" => "EMPTY",
		"AGENT_ORGANIZATION" => "EMPTY",
		"AGENT_ID" => "EMPTY",
		"AGENT_URL" => "EMPTY",
		"AGENT_EMAIL" => "EMPTY",
		"AGENT_PARTNER" => "EMPTY",
		"NOT_FOR_AGENTS" => "EMPTY",
		"HAGGLE" => "EMPTY",
		"MORTGAGE" => "EMPTY",
		"PREPAYMENT" => "EMPTY",
		"RENT_PLEDGE" => "EMPTY",
		"AGENT_FEE" => "EMPTY",
		"WITH_PETS" => "EMPTY",
		"WITH_CHILDREN" => "EMPTY",
		"RENOVATION" => "EMPTY",
		"AREA" => "EMPTY",
		"AREA_UNIT" => "кв.м",
		"LIVING_SPACE" => "EMPTY",
		"LIVING_SPACE_UNIT" => "кв.м",
		"KITCHEN_SPACE" => "EMPTY",
		"KITCHEN_SPACE_UNIT" => "кв.м",
		"LOT_AREA" => "EMPTY",
		"LOT_AREA_UNIT" => "кв.м",
		"LOT_TYPE" => "EMPTY",
		"ROOMS" => "EMPTY",
		"ROOMS_OFFERED" => "EMPTY",
		"NEW_FLAT" => "EMPTY",
		"OPEN_PLAN" => "EMPTY",
		"ROOMS_TYPE" => "EMPTY",
		"PHONE" => "EMPTY",
		"INTERNET" => "EMPTY",
		"ROOM_FURNITURE" => "EMPTY",
		"KITCHEN_FURNITURE" => "EMPTY",
		"TELEVISION" => "EMPTY",
		"WASHING_MACHINE" => "EMPTY",
		"REFRIGERATOR" => "EMPTY",
		"BALCONY" => "EMPTY",
		"BATHROOM_UNIT" => "EMPTY",
		"FLOOR_COVERING" => "EMPTY",
		"WINDOW_VIEW" => "EMPTY",
		"FLOOR" => "EMPTY",
		"FLOORS_TOTAL" => "EMPTY",
		"BUILDING_NAME" => "EMPTY",
		"BUILDING_TYPE" => "EMPTY",
		"BUILDING_SERIES" => "EMPTY",
		"BUILDING_STATE" => "EMPTY",
		"BUILT_YEAR" => "EMPTY",
		"READY_QUARTER" => "EMPTY",
		"LIFT" => "EMPTY",
		"RUBBISH_CHUTE" => "EMPTY",
		"IS_ELITE" => "EMPTY",
		"PARKING" => "EMPTY",
		"ALARM" => "EMPTY",
		"CEILING_HEIGHT" => "EMPTY",
		"PMG" => "EMPTY",
		"TOILET" => "EMPTY",
		"SHOWER" => "EMPTY",
		"KITCHEN" => "EMPTY",
		"POOL" => "EMPTY",
		"BILLIARD" => "EMPTY",
		"SAUNA" => "EMPTY",
		"HEATING_SUPPLY" => "EMPTY",
		"WATER_SUPPLY" => "EMPTY",
		"SEWERAGE_SUPPLY" => "EMPTY",
		"ELECTRICITY_SUPPLY" => "EMPTY",
		"GAS_SUPPLY" => "EMPTY",
		"PRICE_FROM_IBLOCK" => "N",
		"PRICE_REQUIRED" => "Y",
		"PRICE_PERIOD" => "EMPTY",
		"PRICE_UNIT" => "EMPTY",
		"SELF_SALES_NOTES_INPUT" => ""
	),
	false
); ?>
<? require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/footer.php"); ?>
